services:
  db:
    image: postgres:13-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  backend:
    image: benetasks-backend:latest
    build: ./backend
    env_file:
      - ./.env
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  frontend:
    image: benetasks-frontend:latest
    build: ./frontend
    ports:
      - "8000:8000"
      - "8501:8501"
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  app-network:
    driver: overlay
    attachable: true

volumes:
  db_data:
    driver: local